### ISSUE TITLE
HAAPI specification?

### ISSUE THREAD

**Issue by eraviart** [tarfahalrashed/ScrAPIr#2]
Very interesting project!

Is there a (draft) specification of _Human Access to APIs_ (HAAPI)?

**Comment by tarfahalrashed** [comment]
Thank you!
I just added a draft of the HAAPI specification [here](https://github.com/tarfahalrashed/ScrAPIr/blob/master/public/haapi-specification.json)
Not all the fields are required, it depends on what the API requires.

**Comment by eraviart** [comment]
Thanks.
